use_frameworks!

plugin 'cocoapods-keys', {
  :project => "hawk-swift",
  :keys => [
    "HawkKey"
  ]}

target 'HawkSwift_Example' do
  pod 'HawkSwift', :path => '../'

  target 'HawkSwift_Tests' do
    inherit! :search_paths

    
  end
end
